### ISSUE TITLE
plugin won't compile correctly

### ISSUE THREAD

**Issue by kylenstone** [doodzik/metalsmith-google-analytics#1]
Receive an error when I try to build my app with this plugin:

```
Development build, version 1.0.0
/Users/kstone/kylethinks/blog/build.js:60
	.use(googleAnalytics('UA-106228305-1'))
	     ^

TypeError: googleAnalytics is not a function
```

I triple-checked my `build.js` file and I've followed the example in your README exactly.  Does this plugin have a dependency on `metalsmith-each`?

**Comment by doodzik** [comment]
yes, it has a dependency on `metalsmith-each`.
I unfortunately don't have any time to investigate this issue :(
But I will answer any related question.

**Comment by kylenstone** [comment]
No big deal @doodzik, I simply loaded the GA tag as a script in my footer.  No real reason for it to be in a plugin anyways! Cheers.
